USE `stock`;

CREATE TABLE IF NOT EXISTS `users` (
    `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '自增 id',

    `createTime`    datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updateTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`)
) ENGINE = InnoDB, CHARSET=UTF8MB4;

ALTER TABLE `users` ADD COLUMN `xdhuxc_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE `users` ADD COLUMN `abc_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE `users` ADD COLUMN `update_time`    datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';